### ISSUE TITLE
train for other language

### ISSUE THREAD

**Issue by raminrahimi6970** [simplify23/CDistNet#17]
hello thanks for your paper and released codes
I want to train your code for other language but I see in lmdbdataset that you use English char and limit the max length to 30 that is true?
I should change line 245 and 246?

`def __len__(self):
        return self.length

    def get(self,idx):
        with self.env.begin(write=False) as txn:
            image_key, label_key = f'image-{idx+1:09d}', f'label-{idx+1:09d}'
            label = str(txn.get(label_key.encode()), 'utf-8')  # label
            label = re.sub('[^0-9a-zA-Z]+', '', label)
            label = label[:30]`

**Comment by Moonalf** [comment]
I share the same purpose with you. When I removed `label = re.sub('[^0-9a-zA-Z]+', '', label)`，Error occurred: 
`Traceback (most recent call last):
  File "train.py", line 141, in <module>
    main()
  File "train.py", line 137, in main
    train(cfg,args)
  File "train.py", line 114, in train
    do_train(
  File "/data/zch_data/recognition/contrast_exps/CDistNet/cdistnet/engine/trainer.py", line 196, in do_train
    train_loss, train_accu = train(
  File "/data/zch_data/recognition/contrast_exps/CDistNet/cdistnet/engine/trainer.py", line 51, in train
    pred = model(images, tgt)
  File "/home/zhangchunxin/miniconda3/envs/cdistnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zhangchunxin/miniconda3/envs/cdistnet/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zhangchunxin/miniconda3/envs/cdistnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/zch_data/recognition/contrast_exps/CDistNet/cdistnet/model/model.py", line 150, in forward
    sem_feat,sem_mask,sem_key_padding_mask = self.semantic_branch(tgt)
  File "/home/zhangchunxin/miniconda3/envs/cdistnet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/zch_data/recognition/contrast_exps/CDistNet/cdistnet/model/model.py", line 102, in forward
    tgt_mask = generate_square_subsequent_mask(tgt.shape[0]).to(device=tgt.device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.`

**Comment by Moonalf** [comment]
I fixed the problem just now. In config file, we have to make sure that dst_vocab_size matches the size of dst_vocab.
