### ISSUE TITLE
Missing transformer

### ISSUE THREAD

**Issue by j-lootens** [simplify23/CDistNet#7]
When trying to run test.py I get the following error:
```
(CDistNet) C:\<path>\CDistNet>python test.py --i_path ..\examples\300_0.jpg 
configs/CDistNet_config.py
<class 'str'>
Traceback (most recent call last):
  File "test.py", line 175, in <module>
    main()
  File "test.py", line 168, in main
    test_one(cfg, args)
  File "test.py", line 126, in test_one
    en = get_parameter_number(model.transformer.encoder)
  File "C:\<path>\miniconda3\envs\CDistNet\lib\site-packages\torch\nn\modules\module.py", line 1178, in __getattr__ 
    type(self).__name__, name))
AttributeError: 'CDistNet' object has no attribute 'transformer'
```

**Comment by simplify23** [comment]
We fixed some of the code, and it's not clear if test.py will work. Due to time constraints, single image testing is not supported at this stage. Try eval.py to evaluate. Thank you very much

**Comment by j-lootens** [comment]
Thanks, I'll try that
